In [5]:
#Importing required modules
#Code - Slide

import numpy as np

This is sub slide section marked-down

In [21]:
#Sub-slide with code
a = np.array([1, 2, 3])

In [22]:
#Fragment Code
a

array([1, 2, 3])

# We are skipping this

Put some notes here.

In [23]:
a + 10

array([11, 12, 13])

In [9]:
a/3

array([0.33333333, 0.66666667, 1.        ])

In [10]:
a/5

array([0.2, 0.4, 0.6])

In [11]:
a-9

array([-8, -7, -6])

In [15]:
#Fragment after empty cell

In [16]:
#New Slide

In [ ]:
#Fragment to new slide